---
- name:           Ansible pull
  hosts:          localhost
  connection:     local
  become:         yes
  tasks:
  # - debug:
  #     msg:      "{{ansible_env}}"
  - name:         install stuff
    package:
      name:
        - apache2-utils
        - curl
        - evtest
        - ffmpeg
        - git
        - jq
        - lftp
        - lm-sensors
        - mc
        - ncdu
        - python3-pip
        - vim
        - tmux
        - xmlstarlet
        - zsh
      state:      present
      
  - name:         install youtube-dl & asciinema
    pip:
      name:
        - youtube_dl
        - asciinema
      executable: pip3

  - name:         Add cron to do it daily
    cron:
      name:       'ansible-pull '
      minute:     '27'
      hour:       '2'
      user:       "{{ansible_env.SUDO_USER}}"
      job:        ansible-pull -U 'https://github.com/AdamHyski/ansible-pull' pi-zero.yaml

  - name:         install oh-my-zsh
    import_role:
      name: vimes.zsh
