---
- name:           Ansible pull
  hosts:          localhost
  connection:     local
  become:         yes
  tasks:
  # - debug:
  #     msg:        "{{ansible_env}}"
  - name:         install youtube-dl & asciinema
    pip:
      name:
        - youtube_dl
        - asciinema
      executable: pip3
    tags:
      - pip
  - name:         install stuff
    package:
      name:
        - apache2-utils
        - aptitude
        - cmatrix
        - curl
        - evtest
        - ffmpeg
        - git
        - jq
        - lftp
        - lm-sensors
        - lxc
        - mc
        - ncdu
        - python3-pip
        - sl
        - vim
        - xclip
        - tmux
        - xmlstarlet
        - zsh
      state:      present  
  - name: Set timezone variables
    copy: 
      content: "Europe/Warsaw\n"
      dest:     /etc/timezone
      owner:    'root'
      group:    'root'
      mode:     '0644'
      backup:   yes
  - name:         Add cron to do it daily
    cron:
      name:       'ansible-pull '
      minute:     '27'
      hour:       '2'
      user:       "{{ansible_env.SUDO_USER}}"
      job:        ansible-pull -U 'https://github.com/AdamHyski/ansible-pull' playbook.yaml
  
  - name: Add key for influxdb
    ansible.builtin.apt_key:
      url: https://repos.influxdata.com/influxdb.key
      # dest: /etc/apt/trusted.gpg.d/influxdb.asc
      state: present

  - name : Add influxdb to source list 
    ansible.builtin.apt_repository:
      #--- FIX ME ! 
      # repo: deb https://repos.influxdata.com/debian $(lsb_release -cs) stable 
      repo: deb https://repos.influxdata.com/debian buster stable 
      dest: /etc/apt/sources.list.d/influxdb.list
      state: present

  - name: Add key for grafana
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      # dest: /etc/apt/trusted.gpg.d/grafana.asc
      state: present


  - name : Add grafana to source list 
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      dest: /etc/apt/sources.list.d/grafana.list
      state: present

  - name: install stuff
    package:
      name:
        - influxdb
        - grafana
      state: present