---
- name: install all
  hosts: localhost
  connection: local
  become: yes
  vars:
    zsh_theme: nanotech.vimes
    remote_user: adam.hyski
  tasks:
  - name: print
    debug:
      msg: "{{ansible_env}}"
  - name: install youtube-dl & asciinema
    pip:
      name:
        - youtube_dl
        - asciinema
      executable: pip3
    tags:
      - pip
  - name: install stuff
    package:
      name:
        - apache2-utils
        - aptitude
        - cmatrix
        - curl
        - evtest
        - ffmpeg
        - git
        - jq
        - lftp
        - lm-sensors
        - lxc
        - mc
        - ncdu
        - python3-pip
        - sl
        - vim
        - xclip
        - tmux
        - xmlstarlet
        - zsh
      state: present
