---
# tasks file for vimes.grafana
- name: Add key for grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present


- name : Add grafana to source list 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: install grafana
  package:
    name:
      - grafana
    state: present